### ISSUE TITLE
Development bundle.

### ISSUE THREAD

**Issue by funn** [sergei-maertens/django-systemjs#19]
The process is explained here http://jspm.io/0.17-beta-guide/development-bundling.html

It would be great to be able to use it. Libraries like React slow down async module load during development a lot. Maybe we could have some option to enable development bundling, make systemjs_import tag aware of it and load bundle generated by continuously running `python manage.py systemjs_bundle` in watch mode.

**Comment by sergei-maertens** [comment]
The explained process works great, you run the `jspm bundle ... -wid` task separately in another tab. We've been using it for some projects, together with this library.

What we do for example, is run: `jspm bundle imtool/router.js staticfiles/SYSTEMJS/build/router.js -wid`. This injects the bundle config, and with `SYSTEMJS_ENABLED = False`, this does load the development bundle.

We have also set-up some gulp tasks to do the collectstatic stuff, since watchman cannot follow symlinks:

```
'use strict';

var gulp = require('gulp');
var rename = require("gulp-rename");
var watch = require('gulp-watch');

// collecting/copying static files to the STATIC_ROOT (Django), so the watch tasks
// pick them up

// add the folders in STATIC_DIRS here
gulp.task('collectstatic1', function() {
    return watch('src/static/**/*.js', {verbose: true})
        .pipe(gulp.dest('static'));
});

// this watches all the django app dirs, given that an app lives in `src/<project>/<appname>/`
gulp.task('collectstatic2', function() {
    return watch('src/gd/*/static/**/*.js', {verbose: true, base: 'src/gd'})
        .pipe(rename(function(file) {
            var bits = file.dirname.split('/');
            // strip off 'appname' and 'static'
            file.dirname = bits.slice(2).join('/');
            return file;
        }))
        .pipe(gulp.dest('static'));
});

// watch task
gulp.task('default', ['collectstatic1', 'collectstatic2']);
```
We use this successfully with React.

I'm not going to add watch-functionality to this library, for these reasons:

It hides stuff from the end-user, that's my biggest gripe with libraries like django-compressor and django-pipeline. If you already decided to use jspm, then please, embrace it and let the front-end tooling handle the front-end instead of shoehorning it into the backend.

> load bundle generated by continuously running python manage.py systemjs_bundle in watch mode

`systemjs_bundle` is slow, this would have to kick of the jspm bundle with very specific options and it hangs, so it cannot do this for multiple bundles at the same time. Then there's also the thing that output has to be fed back to the shell, output that is already available and nicely formatted from jspm itself. You can also not watch multiple bundles at the same time, since they modify the browser config and one watch task will crash because something else modified the browser config. jspm itself does a great job already at integrating the watch task, so use the right tooling.

**What options are there**

What might be interesting, is adding a command that spits out the `jspm bundle ... -wid` commands for you to run, which you can then add to your `npm scripts`, so you can do `npm run jspm-watch` for example.

Another thing is documenting the gulp config and adding it to the example project(s).

Thoughts and feedback are welcome!

**Comment by sergei-maertens** [comment]
Please see also the discussion at #13

**Comment by funn** [comment]
That's exactly what I need, you cleared most of misunderstandings I had. Thanks for this awesome project :)

**Comment by sergei-maertens** [comment]
Cool, I'll add it on the TODO list to add some extra documentation.

**Comment by pcompassion** [comment]
I have question about the `-wid` and gulp setting.

jspm 0.17 removed defaultJSExtension and we seem to add defaultExtension to every django app with django-jspm setup.  

How did you manage that?

**Comment by sergei-maertens** [comment]
The same setting exists for this library, see the [documentation](http://django-systemjs.readthedocs.io/en/latest/getting_started.html#available-settings). The settings is called `SYSTEMJS_DEFAULT_JS_EXTENSIONS`.

What we have with 0.17 is that in the jspm config files, you have a package config for `myproject`. Imports from `myproject` in the JS files then use that package config, and you can get by without specifying the extension in that case. I prefer to be explicit and try to include the extension everywhere.

For my templatetag, I include the extension as well: `{% systemjs_import '<project>/router.js' %}`.

Does this answer your questions?

**Comment by pcompassion** [comment]
Unfortunately no.


I have `project-root/mysite/apps/app1/static/app1/a.js`

This file gets copied to `project-root/mysite/mysite/static/app1/a.js`

when I run `jspm bundle 'app1/a.js -wid`
It watches files under `project-root/mysite/mysite/static`

Now I need 
```
"app1": {
   "defaultExtension": "js"
}
```
for every django app1, app2... and so on.

You seem to have `project-root/mysite/mysite/static/myproject/app1` .. is that correct?

**Comment by sergei-maertens** [comment]
Ah I see, I actually have `project-root/src/mysite/app1/static/js/app1/foo.js`, which gets collected to `project-root/static/js/app1/foo.js`.

In your case (`project-root/mysite/apps/app1/static/app1/a.js`), the gulp watch pattern would be more like this:

```javascript
// this watches all the django app dirs, given that an app lives in `src/<project>/<appname>/`
gulp.task('collectstatic2', function() {
    return watch('mysite/apps/*/static/**/*.js', {verbose: true, base: 'src/gd'})
        .pipe(rename(function(file) {
            var bits = file.dirname.split('/');
            // strip off 'appname' and 'static'
            file.dirname = bits.slice(2).join('/');
            return file;
        }))
        .pipe(gulp.dest('mysite/mysite/static/'));
});
```
This will copy the file to `project-root/mysite/mysite/static/app1/a.js.

Am I correct that `project-root/mysite/mysite/static/` is your `STATIC_ROOT`?

**Comment by pcompassion** [comment]
Yes that's my `STATIC_ROOT` 
and yes, I can handle watch using `apps/*/static/**/*.js`

My question was for the system.js's config.js 
Because I have STATIC_ROOT/app1, app2 .. instead of STATIC_ROOT/js/app1, app2, 
I need `"app1": {"defaultExtension": "js"}` and so on for every app.. 
Oh well I guess I need to change my file structure;

Thank you for the help!

**Comment by sergei-maertens** [comment]
I'm having a hard time understanding what you mean, can you maybe paste your actual `config.js` contents and some sample js code that does imports?

**Comment by pcompassion** [comment]
project-root/mysite/apps/forum/static/forum/views/posts-view.js  has

```
import PostView from 'forum/views/post-view'; // which is at project-root/mysite/apps/forum/static/forum/views/post-view.js
```

now I need
    "forum": {
      "defaultExtension": "js"
    },
because systemjs starts searching for files from STATIC_ROOT and `forum` is one of the django app I have.

**Comment by sergei-maertens** [comment]
Yes, this is clear. So, in my case I use explicit extensions in the imports:
`import PostView from 'forum/views/post-view.js';`

or, for another project, we have (with jspm 0.17 beta) configured our 'package', so your import would in that case become `import PostView from `'myproject/forum/views/post-view';`.

With jspm we map `myproject` to `js`, so the actual folder where it lives would then become `project-root/mysite/apps/forum/static/js/forum/views/post-view.js`. I believe this is what you mean with re-organizing your file structure. Maybe you could avoid that need with the following (untested) configuration:

```javascript
// jspm.config.js
SystemJS.config({
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/",
      "myproject/": "./" // instead of "js/"
    }
  },
  ...
  transpiler: "plugin-babel",
  packages: {
    "myproject": {
      "format": "esm",
      "main": "main.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {}
        }
      }
    }
  }

// jspm.browser.js
SystemJS.config({
  baseURL: "/static",
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "imtool/": "./" // instead of "js/"
  },
  ...
}
```

**Comment by pcompassion** [comment]
will try that. Thank you.

**Comment by sergei-maertens** [comment]
meh, that sucks, but there's probably a good reason why that is

**Comment by pcompassion** [comment]
BTW, how about switching the order of operation,
bundling first to one of STATIC_DIRS then collectstatic to STATIC_ROOT?

Feels like more natural?

**Comment by sergei-maertens** [comment]
Then you have to fiddle with .gitignore. I suppose it's worth a thought!

**Comment by sergei-maertens** [comment]
Nevermind, I already know why this can't be done - jspm might not be able
to find all the files. It can only find files in a single directory tree,
and django has multiple.

**Comment by pcompassion** [comment]
Is it? 
Doesn't work with `project-root/mysite/apps/` or `project-root/src/mysite/` to jspm:directories:baseURL and set browserConfig:baseURL: to STATIC_URL

I don't know much about systemjs, but if it has one notion of parent directory and notion of parent URL, as django does with STATIC_ROOT and STATIC_URL, it might be possible?

**Comment by sergei-maertens** [comment]
It works in browser with that setup, but not for bundling. Jspm will look
for the file app/foo.js, while it should look for app/static/app/foo.js.

**Comment by pcompassion** [comment]
ah I see.

How about using packages or paths?

packages {
 app1: app1/static/app1
}

Is this still no go because then browser would look for  STATIC_URL/app1/static/app1 ?

**Comment by sergei-maertens** [comment]
Correct
